### ISSUE TITLE
Monitoring inside docker container will crash app

### ISSUE THREAD

**Issue by janantala** [sematext/spm-agent-nodejs#6]
I get following error when I run app inside docker container using node:0.12.7 image. However node:6 works fine.

```
/root/app/node_modules/spm-agent-nodejs/lib/linuxMetrics.js:126
Object.keys(data[cpuName]).forEach(function (cpuProperty) {
^
TypeError: Object.keys called on non-object
at Function.keys (native)
at /root/app/node_modules/spm-agent-nodejs/lib/linuxMetrics.js:126:14
at Array.forEach (native)
at /root/app/node_modules/spm-agent-nodejs/lib/linuxMetrics.js:125:23
at /root/app/node_modules/spm-agent-nodejs/node_modules/procfs-stats/index.js:153:5
at fs.js:334:14
at /root/app/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by otisg** [comment]
Isn't 0.12.7 *ancient* in Node terms?

**Comment by megastef** [comment]
I could reproduce the error message with the offical node:0.12 image. But it did not crash my app. Anyhow the bug is fixed in https://github.com/sematext/spm-agent-nodejs/commit/d0a3eb62d79f9d977659fce5d2401e58bf3e3b3f and npm released 1.29.12 on npm. @janantala  please let me know how it works and wich base image you use. In case of Alpine Linux you might need to add ```RUN apk add --update procps``` to your docker file.

**Comment by janantala** [comment]
Ok thanks. I have tested one legacy app running 0.12.7 as it should be supported according to readme with official node docker image. However I don't need it, I use node 6 primary.

**Comment by megastef** [comment]
The reason was not fully clear, it looks after startup reading from /proc failed (fs or graceful-fs errors), so the new version ignores missing CPU info. In my test CPU usage was readable after a few function calls.
